workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    environment:
      groups:
        - keystore_credentials
        - firebase_credentials
        - distribution_credentials
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - |
        # set up key.properties
        echo $FCI_KEYSTORE | base64 --decode > $FCI_KEYSTORE_PATH
        cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
        storePassword=$FCI_KEYSTORE_PASSWORD
        keyPassword=$FCI_KEY_PASSWORD
        keyAlias=$FCI_KEY_ALIAS
        storeFile=/tmp/keystore.keystore
        EOF
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - flutter build apk --release --build-name=1.0.5 --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/mapping.txt
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        android:
          app_id: $FIREBASE_ANDROID_APP_ID
          groups: 
            - codemagic-testing-group
